### ISSUE TITLE
[BUG] Incompatibilities

### ISSUE THREAD

**Issue by kronos-99** [Muirey03/CentaurIssueReporting#10]
**Describe the bug**
Safe Mode Loop
**To Reproduce**

**Screenshots/Screen recording**
If applicable, add screenshots or a screen recording to help explain your problem.

**Place an "x" between the brackets if true:**
 - [ x] this is a bug others will be able to reproduce
 - [ x] this issue occurs every time and you are able to reliably reproduce it
 - [ x] this issue is present with all other tweaks disabled (using iCleaner Pro)
 - [x ] this issue is present on the latest version of Centaur
 - [ x] this issue is caused by a conflict with another tweak

**Conflicting tweak(s)**
If this issue is caused by a conflicting tweak, what tweak(s) conflict with Centaur?
BetterCCIconsPro
BetterCCXI
CCClearModulesBG
GoodWiFi
KITTLoader
Laetus
LatchKey
**Expected behavior**
Safe Mode
**Device (please complete the following information):**
 - iOS Version: [e.g. iOS8.1]
iPhoneX 11.3.1
**Logs**
If this issue is related to a crash, please provide the applicable crash reports from CrashReporter and Cr4shed.

**Comment by Muirey03** [comment]
Please send me the crash logs from Cr4shed and CrashReporter by pasting them into pastebin

**Comment by kronos-99** [comment]
https://pastebin.com/Hqui7c1E

Cr4shed doesn’t show anything, anything I need to do to set it up?

**Comment by Muirey03** [comment]
Okay, please let me know if this crash still occurs on version 1.0.1 when it is available

**Comment by kronos-99** [comment]
Still crashed...
https://pastebin.com/imSEkHWg

**Comment by Muirey03** [comment]
@kronos-99 Is this still happening with version 1.0.5-2?
