### ISSUE TITLE
[BUG] not compatible is tweak BetterCCIconsPro

### ISSUE THREAD

**Issue by ar2rjke** [Muirey03/CentaurIssueReporting#18]
Modules are incorrectly displayed, a conflict due to tweaks BetterCCIconsPro which removes the background of buttons.

Device (please complete the following information):
Device: [iPhone 8]
iOS Version: [iOS 11.3.1]

![vBIwNlG0VB8](https://user-images.githubusercontent.com/41891409/57984110-e8a3aa80-7a60-11e9-93e8-73d6860ec6dc.jpg)

**Comment by ar2rjke** [comment]
+ not work time 24 hours

**Comment by ar2rjke** [comment]
ADD:

I will describe the problem in detail.
In the tweak settings BetterCCIconsPro there is a function "Change Glyphs Only" when turned on, the module indicators disappear - Centuar.

**Comment by Muirey03** [comment]
After looking into it, I'm afraid there isn't anything I can do about this one as it is a bug in BetterCCIconsPro, not in Centaur. You'll have to contact the developer of BetterCCIconsPro about it, sorry.
