### ISSUE TITLE
[Request] translate buttons "Clear All / Show More"

### ISSUE THREAD

**Issue by ar2rjke** [Muirey03/CentaurIssueReporting#19]
Hello friend, first of all thank you very much for a wonderful and beautiful tweak that is pleasing to the eye.

I have a question, is it possible to translate your tweak in the future, I would like to rename the buttons "Show More, Clear All, No Notifications" translate to Russian, but did not find this setting in the bundles

**Comment by Muirey03** [comment]
Added in v.1.0.2
