### ISSUE TITLE
[BUG] battery color

### ISSUE THREAD

**Issue by tekocheng** [Muirey03/CentaurIssueReporting#21]
while charging battery not coloring in springboard and cc
![07EB0CBF-1E1E-426D-898D-CD88D0B9C8C5](https://user-images.githubusercontent.com/48650357/57987968-0a318000-7abb-11e9-8c95-357b8ddbb146.jpeg)
![54B7953A-4DFD-407F-95EB-0FDA5144018F](https://user-images.githubusercontent.com/48650357/57987969-0a318000-7abb-11e9-9afc-2e42ae3ca0b6.jpeg)

**Comment by Muirey03** [comment]
Fixed in v.1.0.2
