### ISSUE TITLE
[BUG]  after update to 1.0.1, my screen only BLANK. What is this? 

### ISSUE THREAD

**Issue by tryaink** [Muirey03/CentaurIssueReporting#22]
**Describe the bug**

**To Reproduce**

**Screenshots/Screen recording**
If applicable, add screenshots or a screen recording to help explain your problem.

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue occurs every time and you are able to reliably reproduce it
 - [ ] this issue is present with all other tweaks disabled (using iCleaner Pro)
 - [ ] this issue is present on the latest version of Centaur
 - [ ] this issue is caused by a conflict with another tweak

**Conflicting tweak(s)**
If this issue is caused by a conflicting tweak, what tweak(s) conflict with Centaur?

**Expected behavior**

**Device (please complete the following information):**
 - iOS Version: [e.g. iOS8.1]

**Logs**
If this issue is related to a crash, please provide the applicable crash reports from CrashReporter and Cr4shed.

**Comment by tryaink** [comment]
iPhone XR
iOS 12.1 

Screen BLANK when i update to 1.0.1 version
If i use 1.0.0 only respring loop 

Tell me why?

**Comment by Muirey03** [comment]
It will be caused by a conflicting tweak. Please use iCleaner pro to disable all other tweaks, then enable them one-by-one until you find the tweak that caused it. Once you've found it, please tell me so I can get it fixed ASAP

**Comment by tryaink** [comment]
I was disable all other tweak use iCleaner Pro
Only ON Centaur
Not  respring loop
But NOTHING to make CC like Photos (ss) on your description centaur. 

What happened?

**Comment by Muirey03** [comment]
This tweak isn't related to the CC in any way. It is a replacement for the notification center. You can access it by swiping down from the top-middle of the screen, just like on stock. If you find the tweak that was causing your issue, please make a new issue with the name of the tweak so I can fix it.
