### ISSUE TITLE
Network incorrectly reflected

### ISSUE THREAD

**Issue by f0n3h0m3** [Muirey03/CentaurIssueReporting#23]
When evoking Centuar, indicated network is reflected as “4G” even when status bar reflected “LTE”.  Don’t know if it’s a local issue relative to me or every one. 

iPhone 8, 12.1.2, using unc0ver. 
![D5C765B0-9505-4EDB-A766-EA40F23CC364](https://user-images.githubusercontent.com/50809803/57988390-4f21cc00-7a53-11e9-91da-54efdc826978.png)
![1F4B2FAC-56EC-493D-B4E1-54CBF5F764BC](https://user-images.githubusercontent.com/50809803/57988391-4f21cc00-7a53-11e9-9680-b6063f1bc309.png)

**Comment by Muirey03** [comment]
Fixed in v.1.0.2
