### ISSUE TITLE
[BUG] Still not support (Goodges 2)

### ISSUE THREAD

**Issue by moj3ve** [Muirey03/CentaurIssueReporting#24]
(Goodges 2) not support in last update.

**Comment by Muirey03** [comment]
Are you **definitely** using v.1.0.1? If so, please attach a screenshot demonstrating your issue.

**Comment by moj3ve** [comment]
Here is screenshot iPhone 5S ios 11.3.1 Unc0ver jailbreak,
![AA07BA31-09C0-4D03-A7FA-A25CEC8674D9](https://user-images.githubusercontent.com/38189535/58304575-88648e00-7dfd-11e9-9801-53818c8ffaa6.png)
![8344103F-F203-4ADA-80C3-1A902BA86249](https://user-images.githubusercontent.com/38189535/58304577-88648e00-7dfd-11e9-8fa5-5c8a42bc44c9.png)

**Comment by moj3ve** [comment]
Screenshot from last version of centaur 1.0.4

**Comment by Muirey03** [comment]
That is perfectly correct behaviour, no bug there.
