### ISSUE TITLE
[CONFLICT] ShortLook conflict

### ISSUE THREAD

**Issue by alois-gaucher** [Muirey03/CentaurIssueReporting#28]
**Describe the bug**
My messages notifications (SMS, iMessage) doesn’t shows up, even if the phone rings

**To Reproduce**
1. Open notification center
2. Close it
3. Receive a message
4. Notification doesn’t shows up (even the badge on Messages app)

**Screenshots/Screen recording**
I can’t

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue occurs every time and you are able to reliably reproduce it
 - [IDK] this issue is present with all other tweaks disabled (using iCleaner Pro)
 - [X] this issue is present on the latest version of Centaur
 - [Maybe] this issue is caused by a conflict with another tweak

**Conflicting tweak(s)**
For the messages app i just use « Bubbles »

**Device (please complete the following information):**
 - Device: [iPhone X]
 - iOS Version: [iOS 12.1.1 Bêta 3]

**Comment by alois-gaucher** [comment]
Update: disabled shortlook and i think this is a problem with it

**Comment by Muirey03** [comment]
Are you sure this is related to Centaur at all. I think you'll find this still happens if you disable centaur (re-enable all other tweaks please)

**Comment by alois-gaucher** [comment]
I think this is a conflict of Centaur with ShortLook because when i disable ShortLooks it shows up, and if i disable Centaur and enable ShortLook it works fine too

**Comment by Muirey03** [comment]
Enable shortlook and disable Centaur, does the bug still happen?

**Comment by alois-gaucher** [comment]
Not at all, it only happens when ShortLook and Centaur are enabled at the same time

**Comment by Muirey03** [comment]
Okay can I have a little more information? Does it happen with all notifications, or just notifications from the messages app? Do they still appear on the lock screen/in Centaur, or do they not appear anywhere? Do they appear when your device is locked?

**Comment by alois-gaucher** [comment]
No, i only noticed this problem with Messages app. They are not appearing on the lockscreen or centaur, they do not appear anywhere, even the badge on the messages app is not here. I can hear the notification bug nothing shows up

**Comment by Muirey03** [comment]
Can you contact the shortlook developers about this instead please, I don't think there's much I can do about it from my end.

**Comment by alois-gaucher** [comment]
I have an update about this bug, after 1 day more using your tweak, i think i found something more. The problem happens more especially when i receive a message, open the nc, 3D touch the message then reply. After this, the notifications does not appear...
