### ISSUE TITLE
[Request] notifications app open[BUG] 

### ISSUE THREAD

**Issue by ar2rjke** [Muirey03/CentaurIssueReporting#32]
When viewing notifications, you can only clear it - make a swipe to the left, it would not be bad when you open the application to the right when swipe.

Nothing happens when I click on the application, it does not open.

**Comment by Muirey03** [comment]
A single tap on the notification while in the expanded view will open the app

**Comment by ar2rjke** [comment]
ADD:
only works 3DTouch but it does a message preview, but does not open the application.
