### ISSUE TITLE
[BUG]  the close / cancel button does not work

### ISSUE THREAD

**Issue by ar2rjke** [Muirey03/CentaurIssueReporting#33]
I press the button and nothing happens

![sGDMAGRaCrk](https://user-images.githubusercontent.com/41891409/58043520-0eef4600-7b46-11e9-8898-abb8e0cf3d24.jpg)

**Comment by Muirey03** [comment]
Disable your other tweaks and tell me if the bug still happens

**Comment by ar2rjke** [comment]
Disabled all tweaks in icleaner, Left only Centuar the button still does not work.

**Comment by ar2rjke** [comment]
ADD:
iPhone 8
iOS 11.3.1

**Comment by Muirey03** [comment]
Minor issue that I can't fix as I do not own an iOS 11 device, sorry.
