### ISSUE TITLE
[BUG] notifications app open

### ISSUE THREAD

**Issue by ar2rjke** [Muirey03/CentaurIssueReporting#34]
do not rush to close the ticket, please..

When viewing notifications, you can only clear it - make a swipe to the left, it would not be bad when you open the application to the right when swipe.

Nothing happens when I click on the application, it does not open.
only works 3DTouch but it does a message preview, but does not open the application.

Disconnected all tweaks in icleaner, Left only Centuar the application does not open..

**Comment by ar2rjke** [comment]
ADD:
iPhone 8
iOS 11.3.1

**Comment by Muirey03** [comment]
Attach a video demonstrating the issue. Are you sure this is an issue with Centaur? (Some notifications just can't be opened anyway) Please send me two videos, one with **only** centaur enabled where you demonstrate that tapping the notification doesn't open it, and another where **no tweaks** are enabled where you demonstrate opening the **same** notification from the lockscreen by tapping it.

**Comment by Muirey03** [comment]
s0n

**Comment by Link21200** [comment]
So I found out that basically every tweak that messes with the notification settings on ios 11 like intellix, stackxi, privasee, etc. has this problem where tapping the notification doesn’t open the app

**Comment by ar2rjke** [comment]
> So I found out that basically every tweak that messes with the notification settings on ios 11 like intellix, stackxi, privasee, etc. has this problem where tapping the notification doesn’t open the app

Perhaps, but tweaks are disabled - and still does not work ..

**Comment by ar2rjke** [comment]
> Attach a video demonstrating the issue. Are you sure this is an issue with Centaur? (Some notifications just can't be opened anyway) Please send me two videos, one with **only** centaur enabled where you demonstrate that tapping the notification doesn't open it, and another where **no tweaks** are enabled where you demonstrate opening the **same** notification from the lockscreen by tapping it.

I send one video, the problem is visible there (I tested it with iMessage) other applications also do not work.

https://my-files.ru/i3er0p

**Comment by Muirey03** [comment]
What iOS version are you using?

**Comment by ar2rjke** [comment]
iPhone 8
iOS 11.3.1

**Comment by Muirey03** [comment]
I believe this is fixed now in version 1.0.5. If it still doesn't work, tell me and I'll re-open it.
