### ISSUE TITLE
[BUG] Fix turkish ui language texts (actually, inside.)

### ISSUE THREAD

**Issue by Se7Touch** [Muirey03/CentaurIssueReporting#35]
**Describe the bug**

Thank you for turkish language, but have some little bugs

**To Reproduce**

Eng/Tur
Show More        > Daha Fazla
Show Less          > Daha Az
Clear All             > Temizle
No Notification > Bildirim Yok

**Screenshots/Screen recording**

![WhatsApp Image 2019-05-20 at 22 41 40](https://user-images.githubusercontent.com/16725944/58052198-d9a22280-7b5c-11e9-8dee-11389008d32f.jpeg)

**Device (please complete the following information):**
 - Device: [e.g. iPhone8+]
 - iOS Version: [e.g. iOS12.1.1b3]

**Comment by Muirey03** [comment]
If you want to fix up these translations, please modify this, then send me over the fixed version. It would be much appreciated, thanks! https://ghostbin.com/paste/vxmrg. The text being truncated was fixed in version 1.0.2-2 by the way.

**Comment by Se7Touch** [comment]
> If you want to fix up these translations, please modify this, then send me over the fixed version. It would be much appreciated, thanks! https://ghostbin.com/paste/vxmrg. The text being truncated was fixed in version 1.0.2-2 by the way.

Okey, its ready.

https://ghostbin.com/paste/avsxt
