### ISSUE TITLE
[BUG] LTE text gets truncated

### ISSUE THREAD

**Issue by PatrikTheDev** [Muirey03/CentaurIssueReporting#36]
**Describe the bug**
The LTE text gets truncated

**To Reproduce**
1. Turn off wifi and turn on LTE
2. Swipe down to use Centaur
3. Boom, here you have the issue

**Screenshots/Screen recording**
If applicable, add screenshots or a screen recording to help explain your problem.
https://imgur.com/gallery/HlmhlfP
**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue occurs every time and you are able to reliably reproduce it
 - [x] this issue is present with all other tweaks disabled (using iCleaner Pro)
 - [x] this issue is present on the latest version of Centaur
 - [ ] this issue is caused by a conflict with another tweak

**Conflicting tweak(s)**
If this issue is caused by a conflicting tweak, what tweak(s) conflict with Centaur?
None
**Expected behavior**
The LTE text not to be truncated

**Device (please complete the following information):**
 - Device: iP6s
 - iOS Version: iOS12.1.1

**Comment by Muirey03** [comment]
lol congrats on being the first person to use the template correctly

**Comment by Muirey03** [comment]
Fixed in v.1.0.3

**Comment by PatrikTheDev** [comment]
Wen eta 1.0.3 /s

út 21. 5. 2019 v 18:13 odesílatel Tommy Muir <notifications@github.com>
napsal:

**Comment by Muirey03** [comment]
s0n
