### ISSUE TITLE
[BUG] Xen Html springboard widgets go away

### ISSUE THREAD

**Issue by deadman96385** [Muirey03/CentaurIssueReporting#38]
**Describe the bug**
When you activate the the notification drawer, any xen HTML widgets disappear from the springboard

**To Reproduce**
Install a widget to the springboard near the bottom of the screen, swipe to activate the notification drawer and see it disappear.

**Screenshots/Screen recording**
Hopefully that video works
https://share.icloud.com/photos/0j0yfBLer0KPGls5TcpKcVHQw

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [x ] this issue occurs every time and you are able to reliably reproduce it
 - [ ] this issue is present with all other tweaks disabled (using iCleaner Pro)
 - [ x] this issue is present on the latest version of Centaur
 - [ ] this issue is caused by a conflict with another tweak

**Conflicting tweak(s)**
If this issue is caused by a conflicting tweak, what tweak(s) conflict with Centaur?

**Expected behavior**
The widget should stay visible similar to when the cc menu is pulled down (You can see the xen HTML widget through the blur)

**Device (please complete the following information):**
 - Device: iPhone XS Max
 - iOS Version: 12.1.1

**Logs**
If this issue is related to a crash, please provide the applicable crash reports from CrashReporter and Cr4shed.

**Comment by Muirey03** [comment]
This is up to the developer of Xen HTML to fix, there isn't anything I can do about it.
