### ISSUE TITLE
[BUG] fix statusbar

### ISSUE THREAD

**Issue by ar2rjke** [Muirey03/CentaurIssueReporting#39]
On the home screen when calling notifications - the status bar is hidden.
When you enter any application and turn on the notification curtain, the status bar remains, probably this is an error

![4CqO7aO3eeQ](https://user-images.githubusercontent.com/41891409/58202623-b7d1a880-7ce0-11e9-89c1-a6be1a1398bc.jpg)
![7n4CNCeC1cM](https://user-images.githubusercontent.com/41891409/58202629-bacc9900-7ce0-11e9-8cd4-9d3bc9f6b1da.jpg)

**Comment by ar2rjke** [comment]
iPhone 8
iOS: 11.3.1

**Comment by Muirey03** [comment]
This is not a bug. The status bar is hidden on springboard so that it does not go above centaur and get in the way. It does not need to be hidden in apps, so isn't.
