### ISSUE TITLE
[BUG] Tap away to dismiss not works in inside apps

### ISSUE THREAD

**Issue by moj3ve** [Muirey03/CentaurIssueReporting#41]
**Describe the bug**

**To Reproduce**

**Screenshots/Screen recording**
If applicable, add screenshots or a screen recording to help explain your problem.

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue occurs every time and you are able to reliably reproduce it
 - [ ] this issue is present with all other tweaks disabled (using iCleaner Pro)
 - [ ] this issue is present on the latest version of Centaur
 - [ ] this issue is caused by a conflict with another tweak

**Conflicting tweak(s)**
If this issue is caused by a conflicting tweak, what tweak(s) conflict with Centaur?

**Expected behavior**

**Device (please complete the following information):**
 - iOS Version: [e.g. iOS8.1]

**Logs**
If this issue is related to a crash, please provide the applicable crash reports from CrashReporter and Cr4shed.

**Comment by Muirey03** [comment]
Please fill in the template properly including information such as your iOS version, device and whether it still happens after disabling all other tweaks using iCleaner pro.

**Comment by Muirey03** [comment]
Fixed in the next version
