### ISSUE TITLE
[BUG] polish language

### ISSUE THREAD

**Issue by JSzlezak** [Muirey03/CentaurIssueReporting#45]
![C9912612-B06C-4CAB-8D0B-A0C767A365CF](https://user-images.githubusercontent.com/35075699/58368922-c7750b00-7ef3-11e9-9e20-d21c972d3fe4.png)

 - [ x ] this is a bug others will be able to reproduce
 - [ x ] this issue occurs every time and you are able to reliably reproduce it
 - [ x ] this issue is present with all other tweaks disabled (using iCleaner Pro)
 - [ x ] this issue is present on the latest version of Centaur
 - [ ] this issue is caused by a conflict with another tweak

„Clear_all” = „Wyczyść wszystkie”
„Show_more” = „Pokaż więcej”
„No_notifications” = „Brak powiadomień”

**Comment by JSzlezak** [comment]
„Show_less” = „Pokaż mniej”

**Comment by Muirey03** [comment]
This should never happen. Does the text appear correctly when using the english language?

**Comment by JSzlezak** [comment]
![image](https://user-images.githubusercontent.com/35075699/58371539-542ec180-7f12-11e9-96bd-08707b49a155.png)

Yea it looks just right in English

**Comment by Muirey03** [comment]
Has it worked in any versions of Centaur or has it always been broken?

**Comment by Muirey03** [comment]
Nevermind, I've fixed it now, thank you.
