### ISSUE TITLE
[BUG] Can’t access today view at all

### ISSUE THREAD

**Issue by alligatorgangster** [Muirey03/CentaurIssueReporting#49]
**Describe the bug**
I cannot swipe to view the today view (widgets) with this tweak installed 

**To Reproduce**
1. Pull down NC
2. Swiping does nothing. 

**Screenshots/Screen recording**
N/a

**Place an "x" between the brackets if true:**
 - [ x] this is a bug others will be able to reproduce
 - [x ] this issue occurs every time and you are able to reliably reproduce it
 - [x ] this issue is present with all other tweaks disabled (using iCleaner Pro)
 - [x ] this issue is present on the latest version of Centaur
 - [ ] this issue is caused by a conflict with another tweak

**Conflicting tweak(s)**
If this issue is caused by a conflicting tweak, what tweak(s) conflict with Centaur?
N/a

**Expected behavior**

I expect to swipe to view my widgets when viewing my notifications

**Device (please complete the following information):**
 - Device: [e.g. iPhone8
 - iOS Version: [e.g. iOS12.1.2]

**Logs**
If this issue is related to a crash, please provide the applicable crash reports from CrashReporter and Cr4shed.

**Comment by Muirey03** [comment]
This is not a bug. The today view is not part of centaur. You can still access it from the homescreen and lockscreen.

**Comment by alligatorgangster** [comment]
Would it be possible to get a refund then? Especially since it seems you
have no plans to add this back?

The description doesn’t say anything about it replacing the today view as
well as then Notification Center. And not having access to my widgets is a
dealbreaker for me.

Thanks,
Alli

**Comment by Muirey03** [comment]
You can request a refund on the packix website. This tweak completely replaces the notification center, and the today view is part of the notification center, so I'm not quite sure where you expected the today view to be, but as I said it is still accessible from the lockscreen and homescreen. If you really want a refund though, I will accept the request.
