### ISSUE TITLE
[BUG] Ezswipe tweak conflicts with centaur

### ISSUE THREAD

**Issue by osxoz** [Muirey03/CentaurIssueReporting#52]
**Describe the bug**
When i scroll down right, stock nc appears. not centaur 

**Place an "x" between the brackets if true:**
 - [x ] this issue occurs every time and you are able to reliably reproduce it
 - [ x] this issue is present on the latest version of Centaur

**Conflicting tweak(s)**
Ezswipe

.

**Comment by osxoz** [comment]
https://streamable.com/qb34a

video attached

**Comment by Muirey03** [comment]
I don't think there's anything I can really do about this. It's up to the developer of EZ Swipe to add support for centaur, not vice-versa.

**Comment by osxoz** [comment]
Thanks.
