### ISSUE TITLE
[BUG] Tweak doesn’t work on iPad 7,11

### ISSUE THREAD

**Issue by asislife20** [Muirey03/CentaurIssueReporting#55]
**Describe the bug**

**To Reproduce**
1. Go to settings,tweaks,centaur
2. Click on enable, then respring
3. Pull down Notification Center
4. Nothing changes

**Screenshots/Screen recording**
If applicable, add screenshots or a screen recording to help explain your problem.

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x ] this issue occurs every time and you are able to reliably reproduce it
 - [ x] this issue is present with all other tweaks disabled (using iCleaner Pro)
 - [x ] this issue is present on the latest version of Centaur
 - [ ] this issue is caused by a conflict with another tweak

**Conflicting tweak(s)**
If this issue is caused by a conflicting tweak, what tweak(s) conflict with Centaur?
None, still doesn’t work with all other tweaks disabled
**Expected behavior**
Notification Center to change
**Device (please complete the following information):**
 - Device: IPad 7,11 (WiFi)
 - iOS Version: 13.2.2

**Logs**
If this issue is related to a crash, please provide the applicable crash reports from CrashReporter and Cr4shed.

**Comment by asislife20** [comment]
I just notice that the tweak is working but only in portrait mode, not landscape.

**Comment by Muirey03** [comment]
The depiction clearly states: "Please note: Centaur does not work in landscape mode, so I would not recommend using it on an iPad."
