### ISSUE TITLE
[BUG] Installing Grupi breaks Centaur’s notifications 

### ISSUE THREAD

**Issue by Amusingname** [Muirey03/CentaurIssueReporting#57]
**Describe the bug**
Using Grupi and Centaur in tandem breaks Centaur’s notifications.

**To Reproduce**
1. Install Grupi
2. Install Centaur
3. Open Centaur

**Screenshots/Screen recording**
![899FDD9A-9417-4F80-88E5-D48AEE7B1CFA](https://user-images.githubusercontent.com/61616674/75604468-1872ea80-5a96-11ea-8cd6-cd77c7f16d58.png)
![0DA7F571-CC26-4471-8BCB-6160BA190F2F](https://user-images.githubusercontent.com/61616674/75604476-24f74300-5a96-11ea-8101-2d0b63bcb580.png)

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue occurs every time and you are able to reliably reproduce it
 - [X] this issue is present with all other tweaks disabled (using iCleaner Pro) (Except Grupi and Centaur)
 - [X] this issue is present on the latest version of Centaur
 - [X] this issue is caused by a conflict with another tweak

**Conflicting tweak(s)**
Grupi by Soongyu Kwon & Timeloop

**Expected behavior**
For Centaur to display its normal grouped notifications, or for Grupi to be called and substituted in place.

**Device (please complete the following information):**
 - Device: [iPhoneXS]
 - iOS Version: [iOS13.3]

**Logs**
N/A

**Comment by Muirey03** [comment]
The developer of Grupi needs to implement `-[NCNotificationCombinedListViewController ax notification requests]`, this cannot be fixed on Centaur's end.
