### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Nadimo537** [Muirey03/CentaurIssueReporting#62]
Can’t change background and text color

**Screenshots/Screen recording**
If applicable, add screenshots or a screen recording to help explain your problem.

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ x] this issue occurs every time and you are able to reliably reproduce it
 - [x ] this issue is present with all other tweaks disabled (using iCleaner Pro)
 - [x ] this issue is present on the latest version of Centaur
 - [ ] this issue is caused by a conflict with another tweak

**Conflicting tweak(s)**
If this issue is caused by a conflicting tweak, what tweak(s) conflict with Centaur?

**Expected behavior**

**Device (please complete the following information):**
 - iOS Version: [e.g. iOS8.1]

**Logs**
If this issue is related to a crash, please provide the applicable crash reports from CrashReporter and Cr4shed.

**Comment by Muirey03** [comment]
This is a bug in Kalm that breaks libcolorpicker in SpringBoard and not anything to do with Centaur specifically. I have talked with the Kalm developer about it and it will be fixed in the next update to Kalm.
