### ISSUE TITLE
[BUG] UI glitches with an RTL language

### ISSUE THREAD

**Issue by mods2** [Muirey03/CentaurIssueReporting#7]
**Describe the bug**
The time and date are overlapping the battery icon and cellular and wifi signal 

**To Reproduce**
Just when activated
(Swiping down from the top)

**Screenshots/Screen recording**
![Image](https://user-images.githubusercontent.com/36996655/57976867-5a450f80-79f3-11e9-9886-ac4680341042.png)

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [X] this issue occurs every time and you are able to reliably reproduce it
 - [X] this issue is present with all other tweaks disabled (using iCleaner Pro)
 - [X] this issue is present on the latest version of Centaur
 - [ ] this issue is caused by a conflict with another tweak

**Conflicting tweak(s)**
Nothing conflicts

**Expected behavior**
I think this is because my iPhone language is RTL language which is Arabic

**Device (please complete the following information):**
 - Device: [iPhone 8 Plus]
 - iOS Version: [iOS 12.1.1]

**Logs**
There are no logs

**Comment by mods2** [comment]
And I want to make a suggestion for the tweak I'm sure it'll make it better.
If you can enable the swipe up to close it from anywhere on the screen it would be great. having it to close only from the bar on the bottom of it is hard.

**Comment by Muirey03** [comment]
Fixed in v.1.0.1
