### ISSUE TITLE
[BUG] no airplane mode icon when activated

### ISSUE THREAD

**Issue by tekocheng** [Muirey03/CentaurIssueReporting#9]
please add airplane icon and fix compatibility with goodges

**Comment by Muirey03** [comment]
Please attach a screenshot showing the airplane mode bug

**Comment by tekocheng** [comment]
like this

**Comment by Muirey03** [comment]
Fixed in v.1.0.1

**Comment by tekocheng** [comment]
new bugs battery colored white while charging in springboard

**Comment by Muirey03** [comment]
@dotamidplayer don't put that here, make a new issue and fill out all apsects of the template please.
